image: gitpod/workspace-flutter:latest
tasks:
  - command: |
      flutter upgrade
      flutter pub get
      flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0

ports:
  - port: 8080
    onOpen: open-preview
